# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-adaptive-pi"
BBFILE_PATTERN_meta-adaptive-pi = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-adaptive-pi = "6"

LAYERDEPENDS_meta-adaptive-pi = "core"
LAYERSERIES_COMPAT_meta-adaptive-pi = "scarthgap"
