cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED ADAPTIVE_PI_ESBMC_MANIFEST OR NOT EXISTS "${ADAPTIVE_PI_ESBMC_MANIFEST}")
    message(FATAL_ERROR "A generated ESBMC proof manifest is required. Configure the project first.")
endif()
include("${ADAPTIVE_PI_ESBMC_MANIFEST}")
if(NOT proofs)
    message(FATAL_ERROR "The ESBMC proof manifest is empty.")
endif()
file(MAKE_DIRECTORY "${log_directory}")
set(failures "")
foreach(name IN LISTS proofs)
    set(command "${proof_${name}_COMMAND}")
    set(timeout "${proof_${name}_TIMEOUT}")
    set(directory "${proof_${name}_DIRECTORY}")
    set(display "")
    foreach(argument IN LISTS command)
        string(REPLACE "'" "'\\''" argument "${argument}")
        string(APPEND display " '${argument}'")
    endforeach()
    message(STATUS "ESBMC proof ${name} (${timeout}s):${display}")
    execute_process(COMMAND ${command} WORKING_DIRECTORY "${directory}"
        TIMEOUT "${timeout}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error)
    set(log "${log_directory}/${name}.log")
    file(WRITE "${log}" "Directory: ${directory}\nCommand:${display}\nResult: ${result}\n${output}\n${error}")
    set(report "${output}\n${error}")
    if(NOT "${result}" STREQUAL "0" OR NOT report MATCHES "VERIFICATION SUCCESSFUL")
        list(APPEND failures "${name}")
        message(STATUS "ESBMC FAILED: ${name} (${result}); see ${log}\n${output}\n${error}")
    else()
        message(STATUS "ESBMC PASSED: ${name}; see ${log}")
    endif()
endforeach()
if(failures)
    message(FATAL_ERROR "ESBMC proofs failed or were inconclusive: ${failures}")
endif()
