cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED ADAPTIVE_PI_ESBMC_MANIFEST OR NOT EXISTS "${ADAPTIVE_PI_ESBMC_MANIFEST}")
    message(FATAL_ERROR "A generated ESBMC proof manifest is required. Configure the project first.")
endif()
include("${ADAPTIVE_PI_ESBMC_MANIFEST}")
if(NOT proofs)
    message(FATAL_ERROR "The ESBMC proof manifest is empty.")
endif()
file(MAKE_DIRECTORY "${log_directory}")
set(summary "${log_directory}/summary.md")
file(WRITE "${summary}" "# ESBMC proofs\n\nSolver: Z3 (`--z3`).\n\n| Proof | Result | Timeout | Log |\n|---|---|---|---|\n")
set(commands "")
# Hash file contents, file names, and absent paths so edits/additions/deletions
# invalidate evidence. Directory scans run at execution time, not just configure.
function(esbmc_hash_inputs result)
    set(content "")
    foreach(input IN LISTS ARGN)
        set(files "${input}")
        if(IS_DIRECTORY "${input}")
            file(GLOB_RECURSE files LIST_DIRECTORIES FALSE "${input}/*")
            list(SORT files)
        endif()
        string(APPEND content "path:${input}\n")
        foreach(path IN LISTS files)
            if(EXISTS "${path}" AND NOT IS_DIRECTORY "${path}")
                file(SHA256 "${path}" digest)
                string(APPEND content "${path}:${digest}\n")
            else()
                string(APPEND content "${path}:missing\n")
            endif()
        endforeach()
    endforeach()
    string(SHA256 digest "${content}")
    set(${result} "${digest}" PARENT_SCOPE)
endfunction()

if(cache_directory)
    file(MAKE_DIRECTORY "${cache_directory}")
    get_filename_component(tool_directory "${executable}/../.." ABSOLUTE)
    esbmc_hash_inputs(shared_digest ${shared_inputs} "${executable}" "${tool_directory}/include")
endif()
set(failures "")
foreach(name IN LISTS proofs)
    set(command "${proof_${name}_COMMAND}")
    set(timeout "${proof_${name}_TIMEOUT}")
    set(directory "${proof_${name}_DIRECTORY}")
    set(display "")
    foreach(argument IN LISTS command)
        string(REPLACE "'" "'\\''" argument "${argument}")
        string(APPEND display " '${argument}'")
    endforeach()
    set(log "${log_directory}/${name}.log")
    string(APPEND commands "\n## ${name}\n\nWorking directory: `${directory}`\n\n```sh\n${display}\n```\n")
    if(cache_directory)
        esbmc_hash_inputs(input_digest ${proof_${name}_INPUTS})
        string(SHA256 fingerprint "v1;${shared_digest};${input_digest};${command};${timeout};${directory}")
        set(cached_log "${cache_directory}/${name}-${fingerprint}.log")
        if(EXISTS "${cached_log}")
            file(READ "${cached_log}" cached_result)
            if(cached_result MATCHES "Fingerprint: ${fingerprint}" AND cached_result MATCHES "VERIFICATION SUCCESSFUL")
                file(WRITE "${log}" "Reused successful result; inputs unchanged.\n${cached_result}")
                file(APPEND "${summary}" "| ${name} | REUSED | ${timeout}s | `${name}.log` |\n")
                message(STATUS "ESBMC REUSED: ${name}; inputs unchanged; see ${log}")
                continue()
            endif()
        endif()
    endif()
    message(STATUS "ESBMC proof ${name} (${timeout}s):${display}")
    execute_process(COMMAND ${command} WORKING_DIRECTORY "${directory}"
        TIMEOUT "${timeout}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${log}" "Fingerprint: ${fingerprint}\nDirectory: ${directory}\nCommand:${display}\nResult: ${result}\n${output}\n${error}")
    set(report "${output}\n${error}")
    if(NOT "${result}" STREQUAL "0" OR NOT report MATCHES "VERIFICATION SUCCESSFUL")
        list(APPEND failures "${name}")
        message(STATUS "ESBMC FAILED: ${name} (${result}); see ${log}")
        set(verdict "FAILED")
    else()
        message(STATUS "ESBMC PASSED: ${name}; see ${log}")
        set(verdict "PASSED")
        if(cache_directory)
            file(COPY_FILE "${log}" "${cached_log}")
        endif()
    endif()
    file(APPEND "${summary}" "| ${name} | ${verdict} | ${timeout}s | `${name}.log` |\n")
endforeach()
file(APPEND "${summary}" "${commands}")
if(failures)
    message(FATAL_ERROR "ESBMC proofs failed or were inconclusive: ${failures}")
endif()
